baseURL = "http://www.zakolski.com"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en"
paginate = 20
theme = "hugo-coder"
title = "Kamil Zakolski"

[markup.highlight]
noClasses = false

[params]
author = "Kamil"
avatarURL = "images/avatar.jpg"
colorScheme = "auto"
dateFormat = "2 January, 2006"
description = "Kamil Zakolski's personal website"
hideColorSchemeToggle = false
info = ["Senior IT Specialist", "Student"]
keywords = "blog,developer,personal"
maxSeeAlsoItems = 5
rtl = false
since = 2020
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []
# Custom remote JS files
customRemoteJS = []

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[[params.social]]
icon = "fa fa-2x fa-github"
name = "Github"
url = "https://github.com/KamilZakolski/"
weight = 1

[[params.social]]
icon = "fa fa-2x fa-linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/kamilzakolski/"
weight = 2

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

[[languages.en.menu.main]]
name = "Blog"
url = "posts/"
weight = 2

[[languages.en.menu.main]]
name = "Certificates"
url = "cert/"
weight = 3

[[languages.en.menu.main]]
name = "Hardware"
url = "hardware/"
weight = 4

[languages.pl]
languageName = ":poland:"

[languages.pl.params]
description = "Prywatna strona Kamila Zakolskiego"
info = ["Starszy Specjalista IT", "Student"]
keywords = "blog,deweloper,osobisty"

[[languages.pl.menu.main]]
name = "O Mnie"
url = "about/"
weight = 1

[[languages.pl.menu.main]]
name = "Blog"
url = "posts/"
weight = 2

[[languages.pl.menu.main]]
name = "Certyfikaty"
url = "cert/"
weight = 3

[[languages.pl.menu.main]]
name = "SprzÄ™t"
url = "hardware/"
weight = 4
